name: Newman Run

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16
      - name: Install Newman
        run: npm install -g newman
      - name: Run tests
        run: newman run BookCart_automation.postman_collection.json -d books.json
       
      
